/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2018-12-05 12:43:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>AdminLogin</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/forgetPass/css/lrtk.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/idcode/jquery.idcode.css\" />\r\n");
      out.write("<script src=\"http://www.jq22.com/jquery/jquery-1.10.2.js\"></script>\r\n");
      out.write("<script src=\"static/idcode/jquery.idcode.js\"></script>\r\n");
      out.write("<script src=\"static/js/cookie.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/forgetPass/css/lrtk.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 代码 开始 -->\r\n");
      out.write("\t<div id=\"login\">\r\n");
      out.write("\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t\t<form id=\"form1\" method=\"post\" class=\"container offset1 loginform\">\r\n");
      out.write("\t\t\t\t\t<div id=\"owl-login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"hand\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"hand hand-r\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"arms\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"arm\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"arm arm-r\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"pad\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"_csrf\" value=\"gzh\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"account\" class=\"control-label fa fa-user\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"account\" type=\"text\" name=\"account\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Account\" tabindex=\"1\" autofocus=\"autofocus\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control input-medium\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"password\" class=\"control-label fa fa-asterisk\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"password\" type=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"Password\" tabindex=\"2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control input-medium\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t                      \t<input type=\"text\" id=\"Txtidcode\" onchange=\"check()\" class=\"txtVerification\" />\r\n");
      out.write("\t\t                 <span id=\"idcode\"></span>\r\n");
      out.write("\t\t                 </div>\r\n");
      out.write("\t\t                 </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"loginbtn\" type=\"submit\" tabindex=\"4\" disabled=\"false\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn btn-info\">Login</button>\r\n");
      out.write("\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t        $.idcode.setCode();\r\n");
      out.write("\t\t        function check(){\r\n");
      out.write("\t\t\t\tvar IsBy = $.idcode.validateCode(); \r\n");
      out.write("\t\t\t\tif(IsBy==true){\r\n");
      out.write("\t\t\t\t\t document.getElementById(\"loginbtn\").removeAttribute(\"disabled\");\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"验证码错误\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tconsole.log(IsBy);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t        $('#login #password').focus(function() {\r\n");
      out.write("\t\t            $('#owl-login').addClass('password');\r\n");
      out.write("\t\t        }).blur(function() {\r\n");
      out.write("\t\t            $('#owl-login').removeClass('password');\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#loginbtn\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar account = $(\"#account\").val();\r\n");
      out.write("\t\t\t\tvar password = $(\"#password\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar string = \"account=\"+account+\"&password=\"+password;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(account==\"\"||password==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"账号或密码不能为空！\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"http://localhost:8080/ChunYinBackGround/adminLogin\",\r\n");
      out.write("\t\t\t\tdata:string,\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tdataType:\"jsonp\",\r\n");
      out.write("\t\t\t\tsuccess:function(datas){\r\n");
      out.write("\t\t\t\t\tif(datas.code==100){\r\n");
      out.write("\t\t\t\t\t\t//登录成功，创建cookie\r\n");
      out.write("\t\t\t\t\t\tsetCookie(\"account\",account,365);\r\n");
      out.write("\t\t\t\t\t\tsetCookie(\"id\",datas.data.adminId,365);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\twindow.location.href = \"main.jsp\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"账号或密码错误！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(){\r\n");
      out.write("\t\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\treturn false; \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
