/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2018-12-06 03:00:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>纯音后台</title>\r\n");
      out.write("<meta name=\"description\" content=\"这是纯音后台页面\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"index\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"assets/i/favicon.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"assets/i/app-icon72x72@2x.png\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-title\" content=\"Amaze UI\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/amazeui.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/admin.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/app.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"static/bootstrap-3.3.7-dist/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"assets/js/echarts.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"static/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body data-type=\"index\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 头部导航条 -->\r\n");
      out.write("    <header class=\"am-topbar am-topbar-inverse admin-header\">\r\n");
      out.write("        <div class=\"am-topbar-brand\">\r\n");
      out.write("            <a href=\"javascript:;\" class=\"tpl-logo\">\r\n");
      out.write("                <img src=\"assets/img/logo.png\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"am-icon-list tpl-header-nav-hover-ico am-fl am-margin-right\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only\" data-am-collapse=\"{target: '#topbar-collapse'}\"><span class=\"am-sr-only\">导航切换</span> <span class=\"am-icon-bars\"></span></button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"am-collapse am-topbar-collapse\" id=\"topbar-collapse\">\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list tpl-header-list\">\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("                <li class=\"am-hide-sm-only\"><a href=\"javascript:;\" id=\"admin-fullscreen\" class=\"tpl-header-list-link\"><span class=\"am-icon-arrows-alt\"></span> <span class=\"admin-fullText\">开启全屏</span></a></li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"am-dropdown\" data-am-dropdown data-am-dropdown-toggle>\r\n");
      out.write("                    <a class=\"am-dropdown-toggle tpl-header-list-link\" href=\"javascript:;\">\r\n");
      out.write("                    \t<!-- \t\t用户名显示\t\t -->\r\n");
      out.write("                        <span id=\"right_account\" class=\"tpl-header-list-user-nick\">123</span>\r\n");
      out.write("                        <span class=\"tpl-header-list-user-ico\"> <img src=\"assets/img/user01.png\"></span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"am-dropdown-content\">\r\n");
      out.write("                        <li id=\"out\"><a href=\"#\"><span class=\"am-icon-power-off\"></span> 退出</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\" >\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"col-md-2\">\r\n");
      out.write("\t<!-- 左部导航条 -->\r\n");
      out.write("    <div class=\"tpl-page-container tpl-page-header-fixed\">\r\n");
      out.write("        <div class=\"tpl-left-nav tpl-left-nav-hover\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("            <div class=\"tpl-left-nav-title\">\r\n");
      out.write("                ······\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tpl-left-nav-list\">\r\n");
      out.write("                <ul class=\"tpl-left-nav-menu\">\r\n");
      out.write("                    <li class=\"tpl-left-nav-item\">\r\n");
      out.write("                        <a href=\"indextest.jsp\" class=\"nav-link active\" target=\"mainframe\">\r\n");
      out.write("                            <i class=\"am-icon-home\"></i>\r\n");
      out.write("                            <span>首页</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                    <li class=\"tpl-left-nav-item\">\r\n");
      out.write("                        <a href=\"javascript:;\" class=\"nav-link tpl-left-nav-link-list\">\r\n");
      out.write("                            <i class=\"am-icon-table\"></i>\r\n");
      out.write("                            <span>歌曲</span>\r\n");
      out.write("                            <i class=\"am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"tpl-left-nav-sub-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"song_list.jsp?#\" target=\"mainframe\">\r\n");
      out.write("                                    <i class=\"am-icon-angle-right\"></i>\r\n");
      out.write("                                    <span>所有歌曲</span>\r\n");
      out.write("                                    <i class=\"am-icon-star tpl-left-nav-content-ico am-fr am-margin-right\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"song_upload.jsp\" target=\"mainframe\">\r\n");
      out.write("                                    <i class=\"am-icon-angle-right\"></i>\r\n");
      out.write("                                    <span>上传歌曲</span>\r\n");
      out.write("                                    <i class=\"tpl-left-nav-content tpl-badge-success\">\r\n");
      out.write("\t\t\t\t\t\t               18\r\n");
      out.write("\t\t\t\t\t\t             </i>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 歌手管理 -->\r\n");
      out.write("\t\t\t\t\t<li class=\"tpl-left-nav-item\">\r\n");
      out.write("                        <a href=\"javascript:;\" class=\"nav-link tpl-left-nav-link-list\">\r\n");
      out.write("                            <i class=\"am-icon-wpforms\"></i>\r\n");
      out.write("                            <span>作曲人</span>\r\n");
      out.write("                            <i class=\"am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"tpl-left-nav-sub-menu\" style=\"display: block;\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"composer_list.jsp?#\" target=\"mainframe\">\r\n");
      out.write("                                    <i class=\"am-icon-angle-right\"></i>\r\n");
      out.write("                                    <span>所有作曲人</span>\r\n");
      out.write("                                    <i class=\"am-icon-star tpl-left-nav-content-ico am-fr am-margin-right\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<!-- 用户管理 -->\r\n");
      out.write("\t\t\t\t\t<li class=\"tpl-left-nav-item\">\r\n");
      out.write("                        <a href=\"javascript:;\" class=\"nav-link tpl-left-nav-link-list\">\r\n");
      out.write("                            <i class=\"am-icon-wpforms\"></i>\r\n");
      out.write("                            <span>用户</span>\r\n");
      out.write("                            <i class=\"am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"tpl-left-nav-sub-menu\" style=\"display: block;\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"user_list.jsp?#\" target=\"mainframe\">\r\n");
      out.write("                                    <i class=\"am-icon-angle-right\"></i>\r\n");
      out.write("                                    <span>所有用户</span>\r\n");
      out.write("                                    <i class=\"am-icon-star tpl-left-nav-content-ico am-fr am-margin-right\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 评论管理 -->\r\n");
      out.write("                    <li class=\"tpl-left-nav-item\">\r\n");
      out.write("                        <a href=\"javascript:;\" class=\"nav-link tpl-left-nav-link-list\">\r\n");
      out.write("                            <i class=\"am-icon-wpforms\"></i>\r\n");
      out.write("                            <span>评论</span>\r\n");
      out.write("                            <i class=\"am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"tpl-left-nav-sub-menu\" style=\"display: block;\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"song_comments_list.jsp\"  target=\"mainframe\">\r\n");
      out.write("                                    <i class=\"am-icon-angle-right\"></i>\r\n");
      out.write("                                    <span>歌曲评论</span>\r\n");
      out.write("                                    <i class=\"am-icon-star tpl-left-nav-content-ico am-fr am-margin-right\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                <a href=\"sheet_comments_list.jsp\"  target=\"mainframe\">\r\n");
      out.write("                                    <i class=\"am-icon-angle-right\"></i>\r\n");
      out.write("                                    <span>歌单评论</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                   <!--  管理员账号管理 -->\r\n");
      out.write("                    <li id=\"adminManager\" class=\"tpl-left-nav-item\">\r\n");
      out.write("                        <a href=\"javascript:;\" class=\"nav-link tpl-left-nav-link-list\">\r\n");
      out.write("                            <i class=\"am-icon-wpforms\"></i>\r\n");
      out.write("                            <span>管理员</span>\r\n");
      out.write("                            <i class=\"am-icon-angle-right tpl-left-nav-more-ico am-fr am-margin-right tpl-left-nav-more-ico-rotate\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul class=\"tpl-left-nav-sub-menu\" style=\"display: block;\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"admin_list.jsp?#\"  target=\"mainframe\">\r\n");
      out.write("                                    <i class=\"am-icon-angle-right\"></i>\r\n");
      out.write("                                    <span>管理员账号</span>\r\n");
      out.write("                                    <i class=\"am-icon-star tpl-left-nav-content-ico am-fr am-margin-right\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t<!-- main右下角分页 -->\r\n");
      out.write("        <iframe align=\"right\" name=\"mainframe\" width=\"100%\" height=\"100%\" scrolling=\"no\" src=\"indextest.jsp\" frameborder=\"0\" onload=\"javascript:resizeIframe(this);\"></iframe>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    <script src=\"static/js/cookie.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    /* $(function(){\r\n");
      out.write("    \tvar account = getCookie(\"account\");\r\n");
      out.write("    \tvar id = getCookie(\"id\");\r\n");
      out.write("    \tif(account==null || account==\"\"){\r\n");
      out.write("    \t\talert(\"请先登录！\");\r\n");
      out.write("    \t\twindow.location.href = \"login.jsp\";\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\t//为右上角用户名赋值\r\n");
      out.write("    \t\tdocument.getElementById(\"right_account\").innerText = account;\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t//隐藏管理员管理li\r\n");
      out.write("    \t\tdocument.getElementById(\"adminManager\").style.display=\"none\";\r\n");
      out.write("    \t\tif(id==1){\r\n");
      out.write("    \t\t\tdocument.getElementById(\"adminManager\").style.display=\"\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    }); */\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function resizeIframe(obj) {\r\n");
      out.write("\t    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';\r\n");
      out.write("\t  }\r\n");
      out.write("    \r\n");
      out.write("    $(\"#out\").click(function(){\r\n");
      out.write("    \tdelCookie(\"account\");\r\n");
      out.write("    \tdelCookie(\"id\");\r\n");
      out.write("    \twindow.location.href=\"login.jsp\";\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"assets/js/app.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/amazeui.min.js\"></script>\r\n");
      out.write("\t<script src=\"assets/js/iscroll.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
