/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2018-12-06 03:20:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class song_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>歌曲列表</title>\r\n");
      out.write("<meta name=\"description\" content=\"这是一个 index 页面\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"index\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"assets/i/favicon.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"assets/i/app-icon72x72@2x.png\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-title\" content=\"Amaze UI\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/amazeui.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/admin.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/app.css\">\r\n");
      out.write("    <link href=\"static/bootstrap-3.3.7-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"static/js/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"static/js/DateUtils.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-type=\"generalComponents\">\r\n");
      out.write("\r\n");
      out.write("<!-- -----------------------   模态框--------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("<!-- UpdateModal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"update_modal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"myModalLabel\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"modal-title\" id=\"myModalLabel\">修改歌曲信息</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<audio id=\"music\" controls=\"controls\"></audio>\r\n");
      out.write("\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputEmail1\">歌名</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"update_song_name\" name=\"songName\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入歌名\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">演唱者</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"update_song_composername\" name=\"composerName\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入演唱者\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">歌曲地址</label> <input onchange=\"urlchange()\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"update_song_url\" name=\"songUrl\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入歌曲地址\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">图片地址</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"update_song_imageurl\" name=\"songImageUrl\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入图片地址\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">发布时间</label> <input type=\"date\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"update_song_issuedate\" name=\"songIssueDate\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入发布时间\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">热度</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"update_song_hits\" name=\"songHits\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入热度\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">类型</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"update_class_id\" name=\"classId\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入类型\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"exampleInputPassword1\">作者号</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"update_composer_id\" name=\"composerId\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"请输入作者号\"> <span class=\"help-block\"></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("\t\t\t\t\t\tid=\"user_update_btn\">保存</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- -----------------------   模态框--------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"tpl-content-page-title\">\r\n");
      out.write("                \t所有歌曲\r\n");
      out.write("            </div>\r\n");
      out.write("            <ol class=\"am-breadcrumb\">\r\n");
      out.write("                <li><a href=\"#\" class=\"am-icon-home\">首页</a></li>\r\n");
      out.write("                <li><a href=\"#\">歌曲</a></li>\r\n");
      out.write("                <li class=\"am-active\">歌曲列表</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("            <div class=\"tpl-portlet-components\">\r\n");
      out.write("                <div class=\"portlet-title\">\r\n");
      out.write("                    <div class=\"caption font-green bold\">\r\n");
      out.write("                        <span class=\"am-icon-code\"></span> 歌曲列表\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tpl-block\">\r\n");
      out.write("                    <div class=\"am-g\">\r\n");
      out.write("                        <div class=\"am-u-sm-12 am-u-md-6\">\r\n");
      out.write("                            <div class=\"am-btn-toolbar\">\r\n");
      out.write("                                <div class=\"am-btn-group am-btn-group-xs\">\r\n");
      out.write("                                    <button type=\"button\" class=\"am-btn am-btn-default am-btn-success add_btn\"><span class=\"am-icon-plus\"></span> 新增</button>\r\n");
      out.write("                                    <button type=\"button\" id=\"song_delete_all_btn\" class=\"am-btn am-btn-default am-btn-danger\"><span class=\"am-icon-trash-o\"></span> 删除</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"am-u-sm-12 am-u-md-3\">\r\n");
      out.write("                            <div class=\"am-form-group\">\r\n");
      out.write("                                <select id=\"select_box\" onchange=\"classchange();\" data-am-selected=\"{btnSize: 'sm'}\">\r\n");
      out.write("\t\t\t\t\t              <option value=\"0\">所有类别</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"1\">安静</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"2\">浪漫</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"3\">伤感</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"4\">治愈</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"5\">放松</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"6\">孤独</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"7\">感动</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"8\">兴奋</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"9\">快乐</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"10\">思念</option>\r\n");
      out.write("\t\t\t\t\t              <option value=\"11\">清新</option>\r\n");
      out.write("\t\t\t\t\t            </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- 查询功能 -->\r\n");
      out.write("                        <div class=\"am-u-sm-12 am-u-md-3\">\r\n");
      out.write("                            <div class=\"am-input-group am-input-group-sm\">\r\n");
      out.write("                                <input id=\"song_select\" type=\"text\" class=\"am-form-field\">\r\n");
      out.write("                                <span class=\"am-input-group-btn\">\r\n");
      out.write("            <button id=\"song_select_btn\" class=\"am-btn  am-btn-default am-btn-success tpl-am-btn-success am-icon-search\" type=\"button\"></button>\r\n");
      out.write("          </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"am-g\">\r\n");
      out.write("                        <div class=\"am-u-sm-12\">\r\n");
      out.write("                            <form class=\"am-form\">\r\n");
      out.write("                                <table id=\"song_table\" class=\"am-table am-table-striped am-table-hover table-main\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th class=\"table-check\">\r\n");
      out.write("                                            <input type=\"checkbox\" id=\"check_all\" class=\"tpl-table-fz-check\"></th>\r\n");
      out.write("                                            <th class=\"table-id\">ID</th>\r\n");
      out.write("                                            <th class=\"table-title\">歌曲名称</th>\r\n");
      out.write("                                            <th class=\"table-title\">演唱者</th>\r\n");
      out.write("                                            <th class=\"table-title\">时长</th>\r\n");
      out.write("                                            <th class=\"table-title\">发布时间</th>\r\n");
      out.write("                                            <th class=\"table-title\">热度</th>\r\n");
      out.write("                                            <th class=\"table-title\">类型</th>\r\n");
      out.write("                                            <th class=\"table-title\">作者</th>\r\n");
      out.write("                                            <th class=\"table-set\">操作</th>\r\n");
      out.write("                                            <th class=\"table-set\">评论</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        \t<!-- 在song_list.js中显示 -->\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                                <div class=\"am-cf\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"am-fr\">\r\n");
      out.write("                                       <div id=\"page_nav\" class=\"am-fr\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <hr>\r\n");
      out.write("\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tpl-alert\"></div>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- static/js/ -->\r\n");
      out.write("        <script src=\"static/js/cookie.js\"></script>\r\n");
      out.write("    <script src=\"static/js/song_list.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
