/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2018-12-06 03:20:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class song_005fupload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>上传歌曲</title>\r\n");
      out.write("<meta name=\"description\" content=\"上传歌曲\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"index\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"assets/i/favicon.png\">\r\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"assets/i/app-icon72x72@2x.png\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-title\" content=\"Amaze UI\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/amazeui.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/admin.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/app.css\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body data-type=\"generalComponents\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"tpl-content-page-title\">\r\n");
      out.write("                \t上传歌曲\r\n");
      out.write("            </div>\r\n");
      out.write("            <ol class=\"am-breadcrumb\">\r\n");
      out.write("                <li><a href=\"#\" class=\"am-icon-home\">首页</a></li>\r\n");
      out.write("                <li><a href=\"#\">歌曲</a></li>\r\n");
      out.write("                <li class=\"am-active\">上传歌曲</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("            <div class=\"tpl-portlet-components\">\r\n");
      out.write("                <div class=\"portlet-title\">\r\n");
      out.write("                    <div class=\"caption font-green bold\">\r\n");
      out.write("                        <span class=\"am-icon-code\"></span> 上传歌曲\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"tpl-portlet-input tpl-fz-ml\">\r\n");
      out.write("                        <div class=\"portlet-input input-small input-inline\">\r\n");
      out.write("                            <div class=\"input-icon right\">\r\n");
      out.write("                                <i class=\"am-icon-search\"></i>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control form-control-solid\" placeholder=\"搜索...\"> </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"tpl-block \">\r\n");
      out.write("                    <div class=\"am-g tpl-amazeui-form\">\r\n");
      out.write("                        <div class=\"am-u-sm-12 am-u-md-9\">\r\n");
      out.write("                        \r\n");
      out.write("                            <form id=\"song_upload_table\" class=\"am-form am-form-horizontal\">\r\n");
      out.write("                                <div class=\"am-form-group\">\r\n");
      out.write("                                    <label for=\"user-name\" class=\"am-u-sm-3 am-form-label\">歌名</label>\r\n");
      out.write("                                    <div class=\"am-u-sm-9\">\r\n");
      out.write("                                        <input type=\"text\" name=\"songName\" placeholder=\"输入歌名\">\r\n");
      out.write("                                        <small>响亮的名字</small>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"am-form-group\">\r\n");
      out.write("                                    <label for=\"user-email\" class=\"am-u-sm-3 am-form-label\">作曲人</label>\r\n");
      out.write("                                    <div class=\"am-u-sm-9\">\r\n");
      out.write("                                        <input type=\"text\" name=\"composerName\" placeholder=\"输入作曲人\">\r\n");
      out.write("                                        <small>优秀的作者</small>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"am-form-group\">\r\n");
      out.write("                                    <label for=\"user-email\" class=\"am-u-sm-3 am-form-label\">类别</label>\r\n");
      out.write("                                    <div class=\"am-u-sm-9\">\r\n");
      out.write("                                        <select id=\"class_box\" name=\"className\">\r\n");
      out.write("                                        \t<option value=\"1\">安静</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">浪漫</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">伤感</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\">治愈</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\">放松</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"6\">孤独</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"7\">感动</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"8\">兴奋</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"9\">快乐</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"10\">思念</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"11\">清新</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"am-form-group\">\r\n");
      out.write("                                    <label for=\"user_issue_date\" class=\"am-u-sm-3 am-form-label\">发布时间</label>\r\n");
      out.write("                                    <div class=\"am-u-sm-9\">\r\n");
      out.write("                                        <input type=\"text\" name=\"songIssueDate\" placeholder=\"输入发行日期\">\r\n");
      out.write("                                        <small>出生的日子</small>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("                                <div class=\"am-form-group\">\r\n");
      out.write("                                    <label for=\"user-phone\" class=\"am-u-sm-3 am-form-label\">歌曲链接</label>\r\n");
      out.write("                                    <div class=\"am-u-sm-9\">\r\n");
      out.write("                                        <input onchange=\"set_song_time();\" id=\"song_url\" type=\"text\" name=\"songUrl\" placeholder=\"输入歌曲链接\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"am-form-group\">\r\n");
      out.write("                                    <label for=\"user-QQ\" class=\"am-u-sm-3 am-form-label\">封面连接</label>\r\n");
      out.write("                                    <div class=\"am-u-sm-9\">\r\n");
      out.write("                                        <input type=\"text\" name=\"songImageUrl\" placeholder=\"输入封面连接\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("                                <div class=\"am-form-group\">\r\n");
      out.write("                                    <div class=\"am-u-sm-9 am-u-sm-push-3\">\r\n");
      out.write("                                        <button type=\"button\" id=\"add_music\" class=\"am-btn am-btn-primary\">上传歌曲</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<audio id=\"music\" controls=\"controls\" >\r\n");
      out.write("\t\r\n");
      out.write("\t</audio><span id=\"music_prompt\"></span>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/app.js\"></script> \r\n");
      out.write("    <script src=\"static/js/song_upload.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
